import { ObjectType, Field, ID, Float } from '@nestjs/graphql';
import { GraphQLDate } from 'graphql-scalars';

@ObjectType()
export class PopCritValueEntity {
  // * 👷 GraphQL Decorator template
  // @Field(() => Int, {
  //   defaultValue: 'any',
  //   deprecationReason: 'too old',
  //   description: 'Description to display in GraphQL',
  //   nullable: false,
  // })

  // * 🤖 Fields without @Field will have it generated by Nest CLI

  // * Managed by Prisma
  @Field(() => ID, {
    name: 'idPopCritValue',
    description: 'Unique ID',
    nullable: false,
  })
  idPopCritValue: string;

  @Field(() => GraphQLDate, {
    name: 'createdAt',
    description: 'Date of creation',
    nullable: false,
  })
  createdAt: Date;

  @Field(() => GraphQLDate, {
    name: 'updatedAt',
    description: 'Date of last update',
    nullable: false,
  })
  updatedAt: Date;

  // * Cronexia mandatory
  createdBy: string;
  updatedBy?: string;

  // ---

  // * PopCritValue

  @Field(() => Boolean, {
    name: 'valueBol',
    description: 'The value itself, with Boolean type enforcement',
    nullable: true,
  })
  valueBol?: boolean;

  @Field(() => GraphQLDate, {
    name: 'valueDat',
    description: 'The value itself, with Date type enforcement',
    nullable: true,
  })
  valueDat?: Date;

  @Field(() => Float, {
    name: 'valueNbr',
    description: 'The value itself, with Float type enforcement',
    nullable: true,
  })
  valueNbr?: number;

  @Field(() => String, {
    name: 'valueStr',
    description: 'The value, with String type enforced.',
    nullable: true,
  })
  valueStr?: string;

  // ---

  // * 🔗 Relations

  // One to many / Only one 📦
  //      Virtual field, not present in database
  // popCriteria   PopCriteria @relation(fields: [popCriteriaId], popCriterias: [idPopCriteria])

  // Only the scalar, present in database, as a foreign key
  @Field(() => String, {
    name: 'popCriteriaId',
    description: 'Foreign key to PopCriteria',
    nullable: true,
  })
  popCriteriaId?: string;
}
